--liquibase formatted sql

--changeset alekseyz:1

create table if not exists roles
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255)
);

create table if not exists users
(
    id       bigint generated by default as identity
        primary key,
    password varchar(255),
    username varchar(255)
);

create table if not exists tokens
(
    id      bigint generated by default as identity
        primary key,
    expired boolean,
    revoked boolean,
    token   varchar(255)
            unique,
    type    varchar(255),
    user_id bigint
        references users
);

create table if not exists users_roles
(
    user_id bigint not null
         references users,
    role_id bigint not null
         references roles
);

insert into roles (id, name)
values (1, 'ADMIN'),
    (2,'USER');

insert into users (id, password, username)
values (999999999, '$2y$10$zTbWc/ed/uslwgygssYkY.r5ukVufqHp.9vJYaj3HZyReiu3UuyEa', 'ADMIN');

insert into users_roles (user_id, role_id)values (999999999,1);

